# Generated by Django 2.1.7 on 2019-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, upload_to='userimage/')),
                ('Name', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm', models.CharField(help_text='Confirm your password', max_length=100)),
                ('Phone', models.CharField(blank=True, max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('Address', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
